# Generated by Django 3.1.1 on 2022-01-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertables',
            name='actual_table_name',
            field=models.CharField(default='dk', max_length=100),
            preserve_default=False,
        ),
    ]
