# Generated by Django 3.1.1 on 2022-01-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_usertables_actual_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('column', models.CharField(max_length=25)),
                ('filter_type', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.usertables')),
            ],
        ),
    ]
