# Generated by Django 3.1.1 on 2022-01-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_savedfilter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedfilter',
            old_name='service_id',
            new_name='table_id',
        ),
    ]
